### ISSUE TITLE
Typo in paper's equation 3

### ISSUE THREAD

**Issue by zhaoguangyuan123** [complight/realistic_holography#1]
Hi Kaan, 

Did you miss an inverse Fourier transform sign in the third line of Eq.3?

Pls let me know if I misunderstand. 

Best
Guangyuan

**Comment by kaanaksit** [comment]
Hi Guangyuan,

Thank you for showing interest in our work. If I follow correctly, you refer to this specific equation:

![resim](https://user-images.githubusercontent.com/191201/164993532-eedcb008-e672-4d51-a994-324157ba43d3.png)

And if you are referring to the third line, You are correct that there should be an inverse Fourier Transform sign around U0 times H. Thank you for pointing this out!

@KorayKavakli, do you think we can release a correction on Arxiv in the worst case and a correction for Applied Optics in the best case?

Best regards,
Kaan

**Comment by kaanaksit** [comment]
@zhaoguangyuan123 In case you are interested, here is how this bit is implemented:

https://github.com/kunguz/odak/blob/master/odak/learn/wave/classical.py#L93-L131

If you find our work to useful to you anyhow, we kindly ask you to leave us a star in our GitHub repositories :)

**Comment by zhaoguangyuan123** [comment]
> 
Thanks, I have my own implementation.
Directly learning a parameterized prop kernel is an interesting idea.

Best

**Comment by kaanaksit** [comment]
@KorayKavakli gentle reminder for this bug. It is still open.

**Comment by kaanaksit** [comment]
@KorayKavakli this is a gentle reminder for this outstanding issue.

**Comment by KorayKavakli** [comment]
I initiated a version replacement in arxiv with the correction. 
Once it is online, the link will be replaced with the updated version.

**Comment by kaanaksit** [comment]
Thank you @KorayKavakli . This resolves the issue highlighted by @zhaoguangyuan123 . 

@zhaoguangyuan123 please do not hesitate to reopen this issue if necessary. Thank you for letting us know as well!

**Comment by zhaoguangyuan123** [comment]
thank you for letting me know  
cheers
